### ISSUE TITLE
Maybe add a border glow to the icon in the menu bar?

### ISSUE THREAD

**Issue by bitboxer** [bitcrowd/tickety-tick#176]
When I am using dark mode, i barely see the tickety tick icon in the menu bar. Maybe adding a glow border would help it standing out?

**Comment by pmeinhardt** [comment]
Pretty much all browsers use a rather flat UI style without any gradients, shadows or glows.
I'd therefore prefer not to add a glow.

I wonder if there's a way for either providing "light" and "dark" icon versions (e.g. via the extension manifest) or an icon mask that is colored by the browser (something that Apple does for iOS app navbars…)?

🤔

**Comment by pmeinhardt** [comment]
Mmh. There doesn't seem to be a way of providing a different light and dark icons:

- https://developer.chrome.com/extensions/manifest/icons
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/icons

Not sure if it's possible to set the icon on runtime from JavaScript and to query the browser/OS UI mode?

**Comment by bitboxer** [comment]
But what about just modifying the current logo with a little glow to make it work on both dark and bright background?

This is how it looks like on my dark firefox right now:

<img width="70" alt="Screenshot 2019-09-04 at 10 36 55" src="https://user-images.githubusercontent.com/56195/64239127-f3932580-ceff-11e9-97d4-fb0feb30346d.png">

**Comment by pmeinhardt** [comment]
> Pretty much all browsers use a rather flat UI style without any gradients, shadows or glows.
> I'd therefore prefer not to add a glow.

Rather than a glow, a flat light-grey circle in the background might look better. Similar to what it already looks like when you hover the icon. But adding an extra circle or other outline around it also means the logo itself will be even smaller.

![screenshot: hover](https://user-images.githubusercontent.com/706519/64240504-824c7600-cef1-11e9-8624-6dd36f2109d3.png)

If it really bothers you, why not try out a couple of variants and open a PR? 🙂 
I think the difficulty will be to find a version that works for both light and dark themes.

Personally, I also use "dark mode" but since the button stays in the same place, I don't have trouble clicking on it. Most of the time though, I just use the `ctrl+t` shortcut to open the extension popup.

Cheers 👋
