### ISSUE TITLE
Add debugging hints to README

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/tickety-tick#228]
This page contains a couple of hints around debugging an extension (and more):
https://extensionworkshop.com/documentation/develop/debugging/

Could be useful to add this to the "Development" section in our README.

**Comment by klappradla** [comment]
Oh my god, this is pure gold @pmeinhardt 🕵️ 

It's probably best if we simply link to the page itself rather than picking out individual topics and explaining them again ourselves - a) from a standpoint of maintainability and b) since we can hardly estimate what tools people are looking for as this highly depends on the area of the extension one is working on.
