### ISSUE TITLE
Line breaks in command

### ISSUE THREAD

**Issue by SaturnFromTitan** [bitcrowd/tickety-tick#266]
Hi all, thanks for the handy utility - I love it and use it on all my projects :)

Nowadays, when I have a GitHub issue with a longish title, the auto-generated commit message contains unnecessary line breaks and "..."'s.

For instance for the issue:
`"Send docusign error messages to the frontend" #3043`

tickety-tick creates the following command:
```
git checkout -b '3043-send-docusign-error-messages-to-the-frontend' && git commit --allow-empty -m '[#3043] Send docusign error messages to the…

…frontend
'
```

This didn't happen in earlier versions.

I'm on version `4.0.0`.

**Comment by klappradla** [comment]
Hey @SaturnFromTitan 👋 

Happy to hear you use and like the extension 💚

What you are describing happens due to `Tickety-Tick`'s [autoformatting](https://github.com/bitcrowd/tickety-tick#auto-formatting-of-commit-messages) for commit messages. The format is based upon Tim Pope's suggestions in his famous [note about commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) and turned on by default.

You can simply turn of the autoformatting via a checkbox in the [preferences](https://github.com/bitcrowd/tickety-tick#advanced-configuration).

Hope that fixes your problem 🤞
