### ISSUE TITLE
List tickets when multiple issues are on the page

### ISSUE THREAD

**Issue by tessi** [bitcrowd/tickety-tick#28]
On the github issue_s_ page (and probably also on other issue trackers) I expect tickety-tick to show me a list of all currently shown tickets, when I click on the extension. Instead it says, that it could not find any tickets.

@pmeinhardt just told me, I can select (check that checkbox) tickets, which are then shown in tickety-tick.

What I expect is that all tickets are shown in tickety-tick when no issue is selected. When issues are selected, I expect tickety-tick to only show the selected issues.

**Comment by pmeinhardt** [comment]
I quite like @tessi's idea! To me it would make a lot of sense. What about other TT users? @bitboxer, @andreasknoepfle, …?

**Comment by bitboxer** [comment]
this could be a really long list of tickets...but why not

**Comment by tessi** [comment]
I don't know about the others (the jira list of tickets can be quite long), but at least what i see on github is ~20ish tickets. that should be manageable :)

might be good for time reporting ("i've done those tickets this week" -- copy all commit messages and paste them to the client)

**Comment by bitboxer** [comment]
Yes, but we should not do different behavior per ticket system :wink:

**Comment by andreasknoepfle** [comment]
how about we just take the first 10 or so that we see on that page and add show more button :)

**Comment by klappradla** [comment]
This was already partly address by @tessi in https://github.com/bitcrowd/tickety-tick/pull/92 🎉 

I'm not 100% sure if all the things this issue asks for are covered yet 🤔 

- [ ] **Jira backlog / limit number of tickets**
    When selecting multiple ticket in the Jira backlog, I get a list of all of them _(not limited by number of tickets -> just a scollbar)_ ⏬ 
    ![screen shot 2018-10-25 at 15 04 20](https://user-images.githubusercontent.com/3491815/47502709-c6e69a00-d868-11e8-83c0-df7ab079d851.png)

- [ ] **Github issues (selected)**
    When selecting the checkboxes on Github issues, I'll also get all of them in TicketyTick. I'll have an empty list if I don't manually select things ⏬ 
    ![screen shot 2018-10-25 at 15 05 51](https://user-images.githubusercontent.com/3491815/47502865-0f05bc80-d869-11e8-84ce-2c873429e1d5.png)

- [ ] **??? Jira sprint view**
   Not sure what the goals were for this, but when selecting multiple tickets in Jira's sprint view, TicketyTick will only display the one that appears first in the DOM

Does this mean everything in this issue is already covered and we can close it? Or does this need another iteration / more behavior?

**Comment by pmeinhardt** [comment]
Closing this issue for now, as there's some support for lists of tickets already.
Feel free to re-open if you see the need for further improvements ✌️
