### ISSUE TITLE
Chrome setting screen is growing forever

### ISSUE THREAD

**Issue by andreasknoepfle** [bitcrowd/tickety-tick#331]
![foo](https://user-images.githubusercontent.com/239398/144078378-e152aa94-2eb0-4128-91de-8972558a6837.gif)

**Comment by klappradla** [comment]
Turns out the `vw-100` class on the `<body>` tag within our `options.html` makes Chrome increase the `--dialog-width` on the popup forever:

![chrome](https://user-images.githubusercontent.com/3491815/153388497-02ea971d-66e3-4a5c-b817-3fb76a0136b3.gif)

However, just removing the class is also not an ideal solution: the popup will be too big for smaller screens and people won't be able to reach the button to close the dialog 🙈 

Further investigating... 🕵️
