### ISSUE TITLE
GitHub issue label "bug" not recognized

### ISSUE THREAD

**Issue by kisp** [bitcrowd/tickety-tick#401]
Hi,

I am running **tickety-tick** version 5.1.1 on **chromium**.

When I have an issue on github with a label `bug`, I still get a branch name that looks like `feature/...`.

**Comment by klappradla** [comment]
Hey @kisp 👋 

Thanks for reaching out! You're actually reporting on a feature of the GitHub adapter that I haven't been using since ages. And you're right, it's broken at the moment.

GitHub slightly changed their markup in the sidebar, so the adapter does no longer find the label under the same path 🙈

Feel free to open a PR on tickety-tick yourself, otherwise I'll fix this in my next maintenance session and it will be part of the next release.

**Comment by klappradla** [comment]
Took me a while to get back to it @kisp, but the fix is released now. Should already be there in Firefox and hit Chrome within the next hours ⏳
