### ISSUE TITLE
Trying out yarn?

### ISSUE THREAD

**Issue by bitboxer** [bitcrowd/tickety-tick#43]
This project might be an ideal test case to try out yarn. Anyone here want to try that?

@pmeinhardt @weiland ?

**Comment by pmeinhardt** [comment]
I'd be interested in giving yarn a spin. Since they only just made it public though, you can see issues being opened by the minute… I think we could give it an early try on a separate branch to see how well it behaves and then take another serious look in a couple of weeks to check whether things have stabilized and decide whether we want to use it instead of npm in new projects. (And yes, I know, npm has a ton of issues as well) 😃 

What do you think?

**Comment by bitboxer** [comment]
Sounds like a plan 👍

**Comment by pmeinhardt** [comment]
It is probably worth also testing it on a server-side project to check for potential issues in an environment that's different from our development machines.

**Comment by weiland** [comment]
We should definitely give it a try! 🎉

**Comment by pmeinhardt** [comment]
Closing, see PR #48.
