### ISSUE TITLE
Add more shortcuts.

### ISSUE THREAD

**Issue by arnevm123** [bitcrowd/tickety-tick#440]
Hi,

I'd love to see more shortcuts for this plugin (copy branch, message or command to your clipboard without opening the popup).
Would this be possible?

**Comment by klappradla** [comment]
Hi @arnevm123 👋 

Thanks for reaching out! I fear though that while technically possible, adding more shortcuts that interact with the extension **without opening the popup** is not on our roadmap and is not where we want the extension to go 😢 

Let me briefly explain: While the <kbd>ctrl</kbd> <kbd>t</kbd> shortcut is visually obvious to users (it opens the popup menu...), additional _"hidden"_ shortcuts would not be as obvious. People may most likely hit them unintentionally at first... In my personal opinion, this goes beyond the scope of the browser extension. The extension should do its job in it's limited corner, but not try to interfere with the whole browsing experience of its users. Especially since it's not an extension to modify pages.

Does this make sense to you?

I was also wondering: Which key combinations were you thinking of? Wouldn't it be possible to instruct your browser or operating system to take care of them?
