### ISSUE TITLE
New Opera Release

### ISSUE THREAD

**Issue by andreasknoepfle** [bitcrowd/tickety-tick#82]
Seems that opera is currently not accepting submission #69. 
I'm gonna leave this ticket open and update you if something is happening there.

**Comment by tessi** [comment]
should/can we abandon opera?

**Comment by klappradla** [comment]
Well, I think there's a fair enough amount of people actually using Opera out there 🌴 

I just had a quick look at our account and I don't see why we should not be able to upload any new submissions:

![screen shot 2018-10-30 at 10 07 45](https://user-images.githubusercontent.com/3491815/47707361-e8aa9d00-dc2b-11e8-815e-a8761afa69a5.png)

![screen shot 2018-10-30 at 10 07 58](https://user-images.githubusercontent.com/3491815/47707363-e8aa9d00-dc2b-11e8-87f3-e02b2475c5cd.png)

I can do it / try it out. The question for me would more be:
> what are we uploading there?

Is the build the same one as for Chrome 🤔

**Comment by bitboxer** [comment]
When i did it, I just uploaded the chrome zip file. The problem never was the uploading part, but the moderation part on Operas side. They never reviewed/released the package I uploaded. Contacting them using the forum and email never worked. They simply never answered 😢. But maybe that changed and it is back to working again? Give it a try at least 😉. I know one person who swears by opera and would love to get the extension using the opera store.

**Comment by klappradla** [comment]
Thanx @bitboxer 💚 

I'll give it a shot this week then.

**Comment by klappradla** [comment]
Looking at the 🕳 in the Opera submission process up until now, I'll just try to delete the add on and submit it from scratch. Maybe this reaches someone then 🙏

**Comment by klappradla** [comment]
We could however also a bit more nicer to Opera users and include an `opera.zip` build in our release that is under the hood just a renamed `chrome.zip`... 🤔 

This would at least make it a bit more straight forward for Opera users to get the extension up and running even if the _"moderators"_ are lazy.

What do you think?

**Comment by klappradla** [comment]
Ok, Opera 🙈 what the hell.

It looks like they're shutting down their on add-on _"store"_ (or however this is called anyways). Since they switched to running Chromium under the hood, they also include a [own extensio](https://addons.opera.com/en-gb/extensions/details/install-chrome-extensions/) written by their own team to install Chrome extension in Opera -> which works 😉 

Here's the workflow:

1. On opening the Chrome Web Store, one get's a notice to install the Opera <-> Chrome plugin ⏬
    <img width="1520" alt="screen shot 2018-11-02 at 17 50 24" src="https://user-images.githubusercontent.com/3491815/47929073-41966180-dec8-11e8-9404-fb92caeb3fb3.png">
1. Once installed, all the buttons on the store indicate _(in a crazy coloring)_ that one can install these extension in Opera ⏬
    <img width="1520" alt="screen shot 2018-11-02 at 17 50 39" src="https://user-images.githubusercontent.com/3491815/47929075-41966180-dec8-11e8-94f2-c0bb582c7cea.png">
1. Doing so brings one back to Opera's extension page ⏬
    <img width="1520" alt="screen shot 2018-11-02 at 17 50 50" src="https://user-images.githubusercontent.com/3491815/47929076-41966180-dec8-11e8-85fb-0158d9ace305.png">
1. Once installed the add-on works as expected ⏬
    <img width="1603" alt="screen shot 2018-11-02 at 17 51 00" src="https://user-images.githubusercontent.com/3491815/47929077-41966180-dec8-11e8-8b19-7fb34555e15d.png">

Therefore my suggestion: should we just outline this workflow plus how to install the plugin from a local file in the `README` or in a separate `OPERA.md` that we link to from the `README` and just ditch the whole process of having an extension in their store?

I already opened #109 and could extend that with these new documentation bits. What do you think?

**Comment by pmeinhardt** [comment]
FYI: Just received this email from Opera:

> Hello, developers,
> 
> Opera will soon begin testing the auto-moderation system for publishing extensions and extension updates in the Opera add-ons store. This auto-moderation test will analyze extensions to see if they could potentially pass for future automatic publishing. Extensions will not be published as a result of this auto-moderation test.
> 
> The system will verify if your extension update includes proper and detailed metadata, including a privacy policy, license, links to source code and a support page. Comprehensive metadata will increase the likeliness of your extension being auto-published.
> 
> This is the testing phase of the system. The system will be made public in the coming weeks if the testing phase meets our expectations.
> 
> Thank you for your cooperation

**Comment by klappradla** [comment]
🎉 so there's at least someone alive over at Opera 🎉
