### ISSUE TITLE
Pivotal tracker - No title for tickets

### ISSUE THREAD

**Issue by bitboxer** [bitcrowd/tickety-tick#89]
Something changed at pivotal that broke the title in tickety tick. The plugin can't get any title from the tickets anymore.

**Comment by pmeinhardt** [comment]
Hey @bitboxer, thanks for the report 👍 When you have the time, we're always happy about a PR 😉

The Pivotal adapter should be relatively easy to update:

* [`src/common/adapters/pivotal.js`](https://github.com/bitcrowd/tickety-tick/blob/a612e07ec28650521cfaa969cd6026cab6b9f46b/src/common/adapters/pivotal.js)
* [`spec/adapters/pivotal-spec.js`](https://github.com/bitcrowd/tickety-tick/blob/a612e07ec28650521cfaa969cd6026cab6b9f46b/spec/adapters/pivotal-spec.js)

Please don't hesitate to reach out if you can use any help 👋

**Comment by pmeinhardt** [comment]
In case someone has access to a Pivotal project and decides to work on a fix…

We're currently moving adapters over to using ticket system APIs rather than DOM lookups:

* #137 
* #138 

For Pivotal, we'd like to do the same.

This looks like the relevant endpoint documentation:
https://www.pivotaltracker.com/help/api/rest/v5#Story

PRs very welcome 🙂 

Cheers 👋

**Comment by klappradla** [comment]
Since there wasn't any progress on this and nobody here has access (or is actively working with) Pivotal tracker, we unfortunately need to drop the support for it (at least for now). It does not make much sense to advertise we're supporting it if the adapter is fundamentally broken 🚧

**Comment by klappradla** [comment]
This said, I'll close this one and continue with https://github.com/bitcrowd/tickety-tick/issues/199 ⚰
