### ISSUE TITLE
Drop support for Safari

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/tickety-tick#98]
Looking at current desktop browser usage statistics and how much effort it takes to maintain the Safari version of Tickety-Tick, I think that we can drastically decrease the complexity here by dropping support for Safari.

Firefox, Chrome and many other browsers support the *WebExtension API* but Safari is a completely different beast.

**Comment by pmeinhardt** [comment]
Any objections @bitcrowd/bitcrowd-team?

**Comment by tessi** [comment]
I *personally* don't mind dropping Safari support if it's such a maintenance burden. Especially since we have limited support time 

However this is a too used by many people. Maybe we should do a small survey at least in our and the neighboring office on Mondays stand-up if people are using Tickety tick in Safari and, if so, if they are willing to change browsers.

**Comment by tessi** [comment]
trying to come up with more data and less personal opinion, i had a look at [statcounter.com](http://gs.statcounter.com/browser-market-share) (the source for can-i-use) and learned a bunch

<img width="1206" alt="screen shot 2018-10-20 at 21 44 51" src="https://user-images.githubusercontent.com/206108/47259910-81fde480-d4b1-11e8-9ad9-c68097e66329.png">

* safari is a whooping ~15%
* apparently there is a [UC browser](http://www.ucweb.com/) used by more people than firefox. whoar!

Taking desktop-only browsers, the stats are a little different though:

<img width="1216" alt="screen shot 2018-10-20 at 21 49 00" src="https://user-images.githubusercontent.com/206108/47260153-dd31d600-d4b5-11e8-907a-461243071c51.png">

* most safari users seem to be tablets/phones
* i marked browsers with WebExtension support red in the image above
* apparently the official way to install extensions for safari is is via the app store. I think we're not listed there? So we'd loose "only" people who are willing to manually compile from source.


Coming from that data, I'd say we won't loose much if we're dropping safari.

**Comment by pmeinhardt** [comment]
Hey @tessi, that's exactly the same numbers I looked at (I should've really mentioned these before). I think it's safe to say that mobile and tablet usage isn't relevant in this discussion.

As for your last point: Yes, Tickety-Tick is not available through the App Store… 👇 

> To distribute Safari Extensions, you need to be a member of the Apple Developer Program. You’ll also get access to development resources for macOS, iOS, watchOS, and tvOS.

…which means we'd have to pay.

**Comment by pmeinhardt** [comment]
I also found the reason why the extension was looking strange in Safari just now though. So hey, maybe Safari has just earned another chance 😁

**Comment by klappradla** [comment]
☝️ that's a great idea @pmeinhardt and should in my opinion also be best practice for releases on Github. I'd also suggest to add some more information to the git tag (using `annotate` cc @tessi 💚 ) to inform people what actually changed so that those who download and install it manually can decide if they need the new version or not.

I could even imagine that the _build and release_ process can be automated to a certain degree.

**Comment by pmeinhardt** [comment]
Would be great to look into how other JS projects automate the release process…
